{"name": "test_login", "status": "passed", "description": "login with incorrect credentials to test error msg", "attachments": [{"name": "test_login case passed", "source": "0de55cd7-8c4a-4fb6-9afb-c66294c50790-attachment.png", "type": "image/png"}, {"name": "log", "source": "9d3e8af1-b7b0-4c68-a8aa-2bb1214d9a40-attachment.txt", "type": "text/plain"}], "start": 1691685649341, "stop": 1691685656858, "uuid": "476824b4-b8c2-439b-9376-a3b4d57b36ec", "historyId": "2f078d79405d3f51c45393ae5a8e183f", "testCaseId": "2f078d79405d3f51c45393ae5a8e183f", "fullName": "test_cases.test_login.Test_Login#test_login", "labels": [{"name": "story", "value": "Validating error msg by giving wrong inputs"}, {"name": "severity", "value": "normal"}, {"name": "tag", "value": "reggression"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "DESKTOP-LETAKSH"}, {"name": "thread", "value": "25148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}